### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by lancer-wang** [skrimix/twitter_downloader_bot#3]
![image](https://user-images.githubusercontent.com/69783837/236414029-2a7ca880-9a41-46d7-89fd-2d85a9b1b3aa.png)

use docker

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/236414168-36f34686-eb6f-4788-9cba-fe160e6a560e.png)

**Comment by skrimix** [comment]
Tombstone means the tweet cannot be accessed by the scraper, likely it is age-restricted. As these tweets require authentication to view, they are not supported

**Comment by lancer-wang** [comment]
I noticed that some similar projects use Twitter cookies to access age-restricted tweet

Can this project also use cookies for authentication, or is there any method to log in?

**Comment by lancer-wang** [comment]
> Tombstone means the tweet cannot be accessed by the scraper, likely it is age-restricted. As these tweets require authentication to view, they are not supported

I noticed that some similar projects use Twitter cookies to access age-restricted tweet

Can this project also use cookies for authentication, or is there any method to log in?
