### ISSUE TITLE
clone error

### ISSUE THREAD

**Issue by mightycoin97** [skrimix/twitter_downloader_bot#6]
when i clone the repo and run "python main.py" follwing error is shown:
  File "main.py", line 28
    def extract_tweet_ids(update: Update):
                                ^
SyntaxError: invalid syntax

and when i run "python3 main.py" follwing error is shown:
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    def scrape_media(tweet_id: int) -> list[dict]:
TypeError: 'type' object is not subscriptable

**Comment by skrimix** [comment]
First error: Don't use Python 2, it's long deprecated.

Second error: You need to have at least Python 3.9. Maybe even 3.10, I think there are parts that require it.
